# Generated by Django 4.1.7 on 2023-03-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(max_length=15)),
                ('image_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
