# Generated by Django 4.1.7 on 2023-04-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qwer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviceimage',
            name='advice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='qwer.advice'),
        ),
    ]
