# Generated by Django 4.1.7 on 2023-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwer', '0002_alter_adviceimage_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviceimage',
            name='trans_image',
            field=models.ImageField(null=True, upload_to='trans_images/'),
        ),
    ]
