# Generated by Django 4.1.7 on 2023-03-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=10)),
                ('keyword', models.CharField(max_length=20)),
                ('find_image_number', models.IntegerField(max_length=10)),
                ('searh_result_image', models.ImageField(blank=True, upload_to='crawing/%Y/%m/%d')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
