# Generated by Django 4.1.7 on 2023-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='find_image_number',
            field=models.IntegerField(),
        ),
    ]
