# Generated by Django 4.1.7 on 2023-03-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0006_alter_advice_searh_result_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
